SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[t2] (
		[ID]          [int] NOT NULL,
		[TypeVal]     AS ((1)) PERSISTED NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[t2] SET (LOCK_ESCALATION = TABLE)
GO
